/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'care' at '10/31/16 9:16 AM' with Gradle 2.14.1
 *
 * @author care, @date 10/31/16 9:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
